name: Build and publish benchmark

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"   # every day 06:00 UTC (~09:00 Türkiye)

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright (Chromium)
        run: |
          python -m playwright install --with-deps chromium

      - name: Run scraper
        run: |
          python run_benchmark.py

      - name: Publish Excel into docs/
        run: |
          mkdir -p docs
          mv -f Benchmark_Results.xlsx docs/Benchmark_Results.xlsx
          # optional: keep raw dumps for debugging
          if [ -d dumps ]; then mkdir -p docs/dumps && cp -r dumps/*.txt docs/dumps/ || true; fi

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/Benchmark_Results.xlsx docs/dumps || true
          if ! git diff --cached --quiet; then
            git commit -m "Update benchmark: $(date -u +'%Y-%m-%d %H:%M:%S') UTC"
            git push
          else
            echo "No changes."
          fi
